#!/bin/sh

#Vars
Kernel="$(uname -sr)"
Host="$(hostname)"
Shell="$(basename ${SHELL})"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
echo "        ___                 "
echo "       / _ \ _   _ _ __ ____"
echo "      | | | | | | | '__|_  /"
echo "      | |_| | |_| | |   / / "
echo "       \__\_\,__,_|_|  /___|"
echo 
echo "        Host     : $Host    "
echo "        Kernel   : $Kernel  "
echo "        Shell    : $Shell   "
echo "        Username : $HOME    "
echo "        Uptime   : $uptime  "
